### ISSUE TITLE
There is no Button called "Output Labels"

### ISSUE THREAD

**Issue by mohanhops** [jldowns/vatic-docker#4]
after annotation of video, i could not see any button like "Output Labels" as you have mentioned in the "NPSVisionLab/vatic-docker"'s README file.
how can i download annotated files along with co-ordinates json file.

**Comment by mohanhops** [comment]
finally able to see "Output Labels" button.

**Comment by ahrnbom** [comment]
Hack-NLP, can you please clarify where the "Output Labels" button is? Is there anything one needs to do before it appears? Is it a part of the Web UI or something else?

Edit: Finally found it too. I was at the wrong URL, you need to point your browser to the /directory page to see it.
