### ISSUE TITLE
How to use video options?

### ISSUE THREAD

**Issue by hongjo** [jldowns/vatic-docker#5]
Hello. I highly appreciate you sharing vatic-docker. It helps me a lot.

I wonder how to use video options such as adjusting the length of each segment for the video in frames, as the original VATIC suggests - https://github.com/cvondrick/vatic.

In the docker container, the length is 100, but I want to increase it.

Could you tell me how to change the options?

**Comment by jldowns** [comment]
Hey, thanks for checking out the repo. Unfortunately I'm without a
reliable internet connection until the end of the year so I won't be
able to answer any questions until then :-/
